FROM node:12.13.1

WORKDIR /usr/src/app

# add `usr/src/app/node_modules/.bin` to $PATH
ENV PATH usr/src/app/node_modules/.bin:$PATH
COPY package.json /usr/src/app/package.json

RUN npm --verbose install

CMD ["npm", "start"]
